version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crop_classifier_db
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: pass_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
    container_name: backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: crop_classifier_db
      DB_USER: usuario_app
      DB_PASSWORD: pass_app
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./FrontEnd
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
